language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
script:
- npm test
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: dev@adrianhaasler.com
  api_key:
    secure: cVazVec2nPgWh1NImEXdyPHf42IO1goLGQpfla0HndJ0aPgzC2du0D8kF2f6DQDb4Ioii+qzTBaDtzzMOgsN6kbA3OWy/YIUZyy7Q88WWYPAUP33xMsXh+P+xsqXqvH641lS/fE+M1Avp80kwkyDlr4+nIgFjjkUUaT0rYrR9+DSr1OHxqxRm/hn2IqqsvAnHZAvj9mhfrpw3ER64AWz2l1fQ8vo+7sWPa7wi78gI3GYZVX5KBnaRg8phSWkmeOHz1imx8OsTXLJ+fNYYh9vvZf50TNnG8lUS5iKt4tFe1r5lhG06ZfA6Kzj/Y6XS5yvDt8nTeSJrYAG0UKKTI8i3FBnLV0P3MJHkEt2Tq7r8FBMbJ9j0FssPXI9QDhuwDaSB87ppyhWU3LM6/sht0utkCQOV4IdIsFB10sCNUgDra+rYMSih1cWoBi28xoutP4J1f31YD1qZM7UfADJV2qDAEg8bRi+FP8HYtBLCeDzFGoofN5RqGBbZssUgsKtlsQt83AInYmE/huFm6DLm6OrnD88cVzzCsWm6QKNbkyU9V3FKWJ08VE0ROMARhgJBKgc3/PPWXcJ3RueDQ8eu43fqnjlqfX5sk8O+2r0HPWzrtPtygG4vG/9LADdLxKsWU7E9tuoWmpyGq6rQIHEtPlWbVJrrgO4YoCHSL81iPEq/ag=
  on:
    tags: true
    repo: ahaasler/hexo-generator-multilingual-archive
    node: '0.12'
